### ISSUE TITLE
System.NullReferenceException when opening .GEOMETRY.MBIN.PC files

### ISSUE THREAD

**Issue by Gerokusu** [HugoPeters/NMS-Tools#3]
Hello,

I downloaded the two tools (NMS-Extract and NMS-View), and while the extractor works fine (create all MBIN files from PAK files), when I try to open any of these MBIN files in the Viewer, it keeps raising a null pointer exception.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at NMSView.NMSVertex..ctor(BinaryReader handle, NMSSectionStreamDescriptor desc)
   at NMSView.NMSModel.ReadVertices(BinaryReader handle, Int32 SecId, NMSSectionStreamDescriptor StreamDesc)
   at NMSView.NMSModel.Read(BinaryReader handle)
   at NMSView.NMSModel.Read(String fname)
   at NMSView.NMSViewGame.LoadModel(String FileName)
   at NMSView.RenderWin.openGeometryToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

Any idea of how and why it could raise such an exception ?

Thank you very much !

**Comment by hansolocambo** [comment]
This is an abandonware. Check this page : http://nmsmodding.wikia.com/wiki/No_Man%27s_Sky_Modding_Wiki#Beginner_Topics
You'll find the most recent viewer (v 1.3). And much more.
